spring:
  application:
    name: authentication-service

  profiles:
    active: prod

  config:
    import:
      - spring/datasource/datasource.yml
      - classpath:/app/jwt/jwt.yml
      - app/cors/cors.yml